spring.application.name=catalog

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.username=master
#spring.data.mongodb.password=johnalz
#spring.data.mongodb.database=catalog
#spring.data.mongodb.authentication-database=admin
#
#spring.data.mongodb.auto-index-creation=true

logging.level.springframework.data.mongodb=DEBUG

#spring.data.mongodb.uri=mongodb://master:johnalz@localhost:27017/catalog?authSource=admin
